import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import DataProvider from "@/components/DataProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tasty Treat",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: { children: React.ReactNode;}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <DataProvider>{children}</DataProvider>
        </body>
    </html>
  );
}
